name: semgrep
on: [push, pull_request]

jobs:
  run-semgrep:
    name: Scan
    runs-on: ubuntu-latest
    if: (github.actor != 'dependabot[bot]')
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          config:
            p/r2c
            p/owasp-top-ten
            p/r2c-ci
            p/xss
            p/ci
            p/jwt
            p/nodejs
            p/nodejsscan
          auditOn: push
          generateSarif: "1"
      - name: Github Security Dashboard
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: semgrep.sarif
